// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'package:dart_json_mapper/src/model/annotations.dart' as prefix0;
import 'package:flutter_20210911/bean/time_bean.dart' as prefix1;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.JsonSerializable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'TimeBean',
            r'.TimeBean',
            7,
            0,
            const prefix0.JsonSerializable(),
            const <int>[0, 1, 2, 7],
            const <int>[8, 2, 9, 10, 11, 3, 4, 5, 6],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  (time, ip) => b ? prefix1.TimeBean(time, ip) : null
            },
            -1,
            0,
            const <int>[],
            const <Object>[prefix0.jsonSerializable],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(
            r'time',
            32773,
            0,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const <Object>[const prefix0.JsonProperty(name: 't')]),
        r.VariableMirrorImpl(r'ip', 32773, 0, const prefix0.JsonSerializable(),
            -1, 2, 2, const <int>[], const []),
        r.MethodMirrorImpl(
            r'toString',
            131074,
            0,
            -1,
            2,
            2,
            const <int>[],
            const <int>[],
            const prefix0.JsonSerializable(),
            const <Object>[override]),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 0, 3),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 0, 4),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 1, 5),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 1, 6),
        r.MethodMirrorImpl(r'', 0, 0, -1, 0, 0, const <int>[],
            const <int>[0, 1], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'==', 131074, -1, -1, 3, 3, const <int>[],
            const <int>[4], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            65538,
            -1,
            -1,
            -1,
            -1,
            const <int>[],
            const <int>[5],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'hashCode', 131075, -1, -1, 1, 1, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'runtimeType', 131075, -1, -1, 4, 4, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'time',
            33798,
            7,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(r'ip', 33798, 7, const prefix0.JsonSerializable(),
            -1, 2, 2, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'_time',
            32870,
            4,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_ip',
            32870,
            6,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            32774,
            8,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            9,
            const prefix0.JsonSerializable(),
            -1,
            6,
            6,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[prefix1.TimeBean, int, String, bool, Type, Object, Invocation],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'time': (dynamic instance) => instance.time,
        r'ip': (dynamic instance) => instance.ip
      },
      {
        r'time=': (dynamic instance, value) => instance.time = value,
        r'ip=': (dynamic instance, value) => instance.ip = value
      },
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
